import {
    Cascader as ACascader,
    RangePicker as ARangePicker,
    Empty as AEmpty,
    Checkbox as ACheckbox,
    InputNumber as AInputNumber,
    Popover as APopover,
    Col as ACol,
    Row as ARow,
    Table as ATable,
    Space as ASpace,
    Spin as ASpin,
    Tooltip as ATooltip,
    Dropdown as ADropdown,
    Pagination as APagination,
    Form as AForm,
    FormItem as AFormItem,
    Select as  ASelect,
    SelectOption as ASelectOption,
    Switch as ASwitch,
    DatePicker as ADatePicker,
    TimePicker as ATimePicker,
    TreeSelect as ATreeSelect,
    RadioGroup as ARadioGroup,
    Radio as  ARadio,
    Input as AInput,
    InputSearch as AInputSearch,
    Button as AButton,
    Modal as AModal

} from 'ant-design-vue'

import * as AntIco from '@ant-design/icons-vue'

export default {
    AEmpty,
    ACascader,
    ARangePicker,
    APopover,
    ACheckbox,
    AInputNumber,
    ACol,
    ARow,
    ATable,
    ASpace,
    ASpin,
    ATooltip,
    APagination,
    ADropdown,
    AForm,
    AFormItem,
    ASelect,
    ASelectOption,
    ASwitch,
    ADatePicker,
    ATimePicker,
    ATreeSelect,
    ARadioGroup,
    ARadio,
    AInput,
    AButton,
    AInputSearch,
    AModal,
    //图标
    AntIco
}